# Generated by Django 3.2.8 on 2022-02-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggetions',
            name='review',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=10, null=True),
        ),
    ]
