# Generated by Django 3.2.8 on 2022-02-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_suggetions_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggetions',
            name='review',
            field=models.CharField(choices=[('Good', '1'), ('Average', '2'), ('Need To Improve', '3')], max_length=100, null=True),
        ),
    ]
